require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'spec/**/*'

RSpec:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/routes.rb'

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/Output:
  Enabled: false

