version: '3.7'

services:
  postgres:
    image: postgres:15.4-bookworm
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  web:
    build: .
    environment:
      CYPRESS: $CYPRESS
    volumes:
      - .:/app_home
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
volumes:
  postgres: {}
