default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  host: postgres
  database: sum_development

test:
  <<: *default
  host: postgres
  database: sum_test

production:
  <<: *default
  database: sum_production
  host: 127.0.0.1
  username: sum
  password: ENV['DB_PASSWORD']
