service: sum-dev
image: travisdock/sum-dev

servers:
  - 143.198.160.36

ssh:
  user: 'root'
  keys: ["/home/user/.ssh/id_ed25519"]

proxy:
  ssl: true
  host: dev.sum-finance.com
  app_port: 3000

builder:
  arch: amd64
  dockerfile: Dockerfile.prod

registry:
  username: travisdock
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - SECRET_KEY_BASE
  clear:
    SOLID_QUEUE_IN_PUMA: true

volumes:
  - "/app_storage/sum-dev:/rails/storage"

asset_path: /rails/public/assets


