service: sum-dev
image: sum-dev
servers:
  web:
    hosts:
      - 143.198.160.36
    labels:
        traefik.http.routers.sum-dev.rule: Host(`dev.sum-finance.com`)
        traefik.http.routers.sum-dev.entrypoints: websecure
        traefik.http.routers.sum-dev.tls: true
        traefik.http.routers.sum-dev.tls.certresolver: letsencrypt
ssh:
  user: 'root'
  keys: ["/home/user/.ssh/id_ed25519"]

builder:
  dockerfile: Dockerfile.prod

registry:
  server: ghcr.io/travisdock
  username: travisdock
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - SECRET_KEY_BASE

volumes:
  - "storage:/rails/storage"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json" # To save the configuration file.
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure # We want to force https
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "travisdock@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json" # Must match the path in `volume`
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web # Must match the role in `servers`
