# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
production:
  recurring_entries:
    command: "Recurrable.create_occurrences"
    schedule: at 12am every day
  testing_it:
    command: "Rails.logger.error 'wow'"
    scheudle: every minute
