name: Production Deploy

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: production

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.prod --tag $IMAGE_NAME

    - name: Log in to registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: |
        IMAGE_TAG=$(date +%s)
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        echo "$IMAGE_NAME $IMAGE_ID:$IMAGE_TAG"
        # Push a timestampes image
        docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG
        # Push image as latest
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server via script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY}}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: ./deploy.sh

