name: Production Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: production

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        IMAGE=$IMAGE_NAME:$(date +%s)
        docker build . --file Dockerfile.prod --tag $IMAGE
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/{{ env.IMAGE }}
        docker push $IMAGE_ID
